name: 'Efficiency'
description: 'Estimates efficiency of repo'
inputs:
 file: 
  description: "File to check for efficiency"
  required: true
  default: "/main.py"
 repo:
  description: "Repo to check for efficiency"
  required: true
 ref:
  description: "Branch or tag to checkout"
  default: "master"
  required: false
outputs:
 paths:
  value: ${{ steps.py.outputs.paths }}
  description: "All files checked"
runs:
 using: composite
 steps:
   - name: Checkout Repository 
     uses: actions/checkout@v3.0.2
     with:
      repository: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
   - name: Setup Python
     uses: actions/setup-python@v4
     with: 
      python-version: '3.7'
      cache: 'pip'
     shell: bash
   - run: pip install -r requirements.txt
     id: py
   - name: Execute Python
     env: 
      INPUT_PATH: ${{ inputs.path }}
     run: python ${{ github.action_path }}/main.py
