

name: 'Efficiency'
description: 'Estimates efficiency of repo'
inputs:
 file: 
  description: "File to check for efficiency"
  required: true
  default: "/main.py"
 repo:
  description: "Repo to check for efficiency"
  required: true
 ref:
  description: "Branch or tag to checkout"
  default: "master"
  required: false
outputs:
 paths:
  value: ${{ steps.py.outputs.paths }}
  description: "All files checked"
runs:
 using: composite
 steps:      
   - uses: actions/setup-python@v4
   - uses: actions/checkout@v2
   - uses: BSFishy/pip-action@v1
     with:
      packages: |
       scikit-learn
       javalang
       regex
   - run: python main.py 
